source 'https://rubygems.org'

gem 'rails', '4.2.5'
gem 'jquery-minicolors-rails', path: '../'

gem 'coffee-rails', '~> 4.1.0'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'simple_form'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'spring'
  gem 'web-console', '~> 2.0'
end

